### ISSUE TITLE
TypeError in `qlm_to_qiskit` method due to Non-Iterable Circuit Object

### ISSUE THREAD

**Issue by iamashwin99** [myQLM/myqlm-interop#13]
The qiskit_interop module encounters an error when converting a `qat.comm.datamodel.ttypes.Circuit` object to a Qiskit circuit object. The error occurs in converters.py at line 661 (https://github.com/myQLM/myqlm-interop/blob/f54b7b52eae7758662e22ed13ef46b36a22e96c3/qat/interop/qiskit/converters.py#L661 )

A job received from qlmaas is of the type `qat.comm.datamodel.ttypes.Circuit`  and when passed to `qlm_to_qiskit` the following error is found
```
Traceback (most recent call last):
File "qat/comm/qpu/QPU.py", line 299, in qat.comm.qpu.QPU.Processor.process_submit_job
File "$PROJECT_DIR/qiskit_interface.py", line 95, in submit_job
   qiskit_circuit = self._compile_circuit(job)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "$PROJECT_DIR/qiskit_interface.py", line 156, in _compile_circuit
   qiskit_circuit = qlm_to_qiskit(job.circuit)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "$VENV/lib/python3.11/site-packages/qat/interop/qiskit/converters.py", line 661, in qlm_to_qiskit
   for gate_op in qlm_circuit:
TypeError: 'Circuit' object is not iterable
```

This is solved by explicitly using `qlm_circuit.ops` in the for loop:
```python 
    for gate_op in qlm_circuit.ops:
[ ... ]
```
Maybe this can be considered by default as a solution?

**Comment by ArnaudAtos** [comment]
Dear @iamashwin99,

Thanks for reporting this bug. The class `qat.comm.datamodel.ttypes.Circuit` is an internal structure not designed to be used in the stack. Class `qat.core.Circuit` should be prefered.

If needed, you can translate a `qat.comm.datamodel.ttypes.Circuit` into `qat.core.Circuit` using:

```python
from qat.core import Circuit

raw_circ = ...  # Instance of qat.comm.datamodel.ttypes.Circuit
new_circ = Circuit.from_thrift(raw_circ)
```

Using `for gate_op in qlm_circuit.ops` may cause error in advanced cases. In myQLM, a user can create a routine _(i.e., a sequence a quantum gates)_ but this routine can be seen as a single operator in `qlm_circuit.ops` and it therefor than translable in Qiskit as it is.
Iterating on a circuit `for gate_op in qlm_circuit` will recursively iterate on all the gates.

Nevertheless, I guess you spotted a bug. You were not supposed to manipulate an instance of qat.comm.datamodel.ttypes.Circuit` in the first place.
Did a myQLM function gave you a such object?
